---
title: "Lake Bernard"
output:
  github_document:
    toc: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(cowplot)
library(lubridate)
library(grid)
library(gridExtra)
library(interactions)
library(cowplot)
library(gtExtras)
library(MVZlibrary)
theme_set(theme_cowplot())

source(here("analysis", "functions.R"))
```

## Water levels

Water level data were downloaded using the HYDAT database [here](https://wateroffice.ec.gc.ca/index_e.html); data from 2005-2025 were downloaded using the "historic" database while data from 2026 were downloaded using the real-time database tool for the Lake Bernard station (02EA020 - BERNARD LAKE AT SUNDRIDGE).

### Import and tidy data

```{r}
hist <- read_csv(here("data/daily_20260812T1753.csv"))
current <- read_csv(here("data/02EA020_HGD_20260812T1940.csv")) %>% 
  rename(Date = Date_est, Value = `Value_(m)`)

hist$Date <- lubridate::ymd(hist$Date)
current$Date <- lubridate::ymd(current$Date)

# Combine historic and current data
levels <- bind_rows(hist %>% dplyr::select(Date, Value),
                    current %>% dplyr::select(Date, Value)) %>% 
  mutate("Year" = year(Date),
         "DOY" = yday(Date)) %>% 
  na.omit()

# Calculate monthly min, max, and average
summary <- levels %>% 
  # Only calculate for 2025 and earlier
  filter(!Year == 2026) %>% 
  group_by(DOY) %>% 
  summarize(Average = mean(Value),
            Maximum = max(Value),
            Minimum = min(Value))

doy_months <- read_tsv(here("data/DOY_months.txt"))
```

### Build plot

```{r}
plot_max <- summary %>% na.omit() %>% summarize(max(Maximum)) %>% pull(1)
plot_min <- summary %>% na.omit() %>% summarize(min(Minimum)) %>% pull(1)

ggplot() +
  # Add month bars
  geom_rect(data = doy_months %>% 
              filter(Month %in% c("Jan", "Mar", "May", "Jul", "Sep", "Nov")), 
            aes(xmin = Start, xmax = End, 
                ymin = plot_min-0.1, ymax = plot_max+0.1),
            fill = "grey", alpha = 0.5) +
  # Add min and max levels
  geom_ribbon(data = summary,
              aes(x = DOY, ymin = Minimum, ymax = Maximum), 
              fill = "dodgerblue1", alpha = 0.5) +
  # Add average over all years
  geom_line(data = summary,
            aes(x = DOY, y = Average), 
            color = "dodgerblue1", linetype = "dashed", linewidth = 1) +
  # Add 2025-6 data on top
  geom_line(data = levels %>% 
              filter(Year == 2025), 
            aes(x = DOY, y = Value), 
            linewidth = 1,
            color = "coral") +
  geom_line(data = levels %>% 
              filter(Year == 2026), 
            aes(x = DOY, y = Value), 
            linewidth = 1,
            color = "darkred") +
  ylab("Water level (m)") +
  xlab("Day of the Year") +
  theme(panel.grid.major.y = element_line(linewidth = 0.5, linetype = "dashed", color = "grey")) +
  ggtitle("Lake Bernard") +
  theme(legend.position = "bottom",
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(breaks = (doy_months$Start + doy_months$End) / 2,
                     labels = doy_months$Month,
                     expand = c(0, 0))

# Save plot
ggsave(here("plots/LakeBernard_levels.pdf"), width = 10, height = 5)
```